apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detect-ai-agent # name of the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-detect-ai-agent-app # label for the deployment
  template:
    metadata:
      labels:
        app: face-detect-ai-agent-app # label for the pod
    spec:
      containers:
      - name: face-detect-ai-agent-app # name of the container
        image: us-central1-docker.pkg.dev/face-detect-ai-agent/face-detection-ai-agent/face-detect-ai-agent:latest
        ports:
        - containerPort: 5000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: face-detect-secrets
              key: GROQ_API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: face-detect-service
spec:
  selector:
    app: face-detect-ai-agent-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
