apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detect-ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-detect-ai-agent
  template:
    metadata:
      labels:
        app: face-detect-ai-agent
    spec:
      containers:
      - name: face-detect-ai-agent
        image: us-central1-docker.pkg.dev/gen-lang-client-0729539659/face-detect-repo/face-detect-ai-agent:latest
        ports:
        - containerPort: 5000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: face-detect-secrets
              key: GROQ_API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: face-detect-service
spec:
  selector:
    app: face-detect-ai-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
