version: 2.1

executors:
  docker-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker CLI
          command: |
            curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-24.0.7.tgz | tar xz --strip-components=1 -C /usr/local/bin docker/docker
            docker --version
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            rm -f gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - run:
          name: Build and Push Image
          command: |
            docker build -t us-central1-docker.pkg.dev/face-detect-ai-agent/face-detection-ai-agent/face-detect-ai-agent:latest .
            docker push us-central1-docker.pkg.dev/face-detect-ai-agent/face-detection-ai-agent/face-detect-ai-agent:latest

  deploy_to_gke:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            gcloud components install kubectl --quiet
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            rm -f gcp-key.json
      - run:
          name: Configure GKE
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f kubernetes-deployment.yaml --validate=false
            kubectl rollout restart deployment face-detect-ai-agent

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image